pipeline {
    agent any

    stages {
        stage ('Checking Maven ENV Is Set ') {
            steps {
                build quietPeriod: 1, job: 'FirstJob'
            }
        }
        
        stage('Trigger_Automation_API_Framework') {
            steps {
                build quietPeriod: 2, job: 'Practise_API'
            }
        }
        
        stage('Release Messege') {
            steps {
                build quietPeriod: 2, job: 'Release_Job'
            }
        }
    }
}
